# Generated by Django 4.0.1 on 2022-02-01 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_alter_task_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'priority', 'completed')},
        ),
    ]
